"use client";

import * as Dialog from "@radix-ui/react-dialog";
import Link from "next/link";
import { useState } from "react";
import {
  AlertTriangle, ArrowLeft, Award, BarChart3, BookOpen, CheckCircle2, Circle, FileCheck2,
  GraduationCap, LayoutDashboard, ListTodo, Pencil, Plus, Sparkles, Target, Trash2,
  TriangleAlert, Users, X
} from "lucide-react";
import { useStudents } from "@/components/student-provider";
import { HonorItem, LanguageTestType, SchoolLevel, Student, StudentFormValues, StudentHonors, studentTarget, TargetSchool } from "@/lib/students";

const nav = [
  [LayoutDashboard, "工作台"], [Users, "学生管理"], [FileCheck2, "申请管理"],
  [BookOpen, "院校库"], [Sparkles, "AI 规划助手"], [BarChart3, "月度报告"],
  [TriangleAlert, "风险提示"]
] as const;

export default function StudentDetailPage({ params }: { params: { id: string } }) {
  const { students, hydrated, updateStudent, updateTargetSchools, updateHonors, error } = useStudents();
  const [editOpen, setEditOpen] = useState(false);
  const [schoolEditing, setSchoolEditing] = useState(false);
  const [draftSchools, setDraftSchools] = useState<TargetSchool[]>([]);
  const [honorsEditing, setHonorsEditing] = useState(false);
  const [draftHonors, setDraftHonors] = useState<StudentHonors>({ activities: [], competitions: [] });
  const student = students.find((item) => item.id === params.id);

  if (!hydrated) return <div className="grid min-h-screen place-items-center bg-[#f7f9f8] text-sm text-slate-400">正在读取学生档案...</div>;
  if (!student) return <div className="grid min-h-screen place-items-center bg-[#f7f9f8] px-4 text-center"><div><p className="text-lg font-semibold">未找到该学生</p><p className="mt-2 text-sm text-slate-400">该档案可能已被删除。</p><Link href="/" className="mt-5 inline-flex h-10 items-center rounded-xl bg-brand-600 px-4 text-sm font-medium text-white">返回学生列表</Link></div></div>;

  const languageLabel = student.languageTest.type || "语言成绩";
  const languageScore = student.languageTest.score || "暂无";

  return <div className="min-h-screen bg-[#f7f9f8]">
    <aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-slate-200 bg-white px-4 py-5 lg:block"><div className="flex items-center gap-3 px-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-600 text-white"><GraduationCap size={20}/></span><div><p className="font-semibold tracking-tight">玖肆留学</p><p className="text-[11px] text-slate-400">Jiusi Education</p></div></div><nav className="mt-9 space-y-1">{nav.map(([Icon, label]) => <Link key={label} href={label === "学生管理" ? "/" : "#"} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${label === "学生管理" ? "bg-brand-50 font-medium text-brand-700" : "text-slate-500 hover:bg-slate-50 hover:text-slate-800"}`}><Icon size={18}/>{label}</Link>)}</nav></aside>
    <main className="lg:pl-64">
      <header className="flex h-16 items-center border-b border-slate-200 bg-white/90 px-4 backdrop-blur md:px-8"><span className="text-sm text-slate-400">学生管理</span><span className="mx-3 text-slate-300">/</span><span className="text-sm font-medium">学生详情</span></header>
      <div className="mx-auto max-w-[1300px] p-4 md:p-8">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-500 transition hover:text-brand-700"><ArrowLeft size={16}/>返回学生列表</Link>
        {error && <div role="alert" className="mt-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
        <section className="mt-5 flex flex-col gap-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-card sm:flex-row sm:items-center sm:justify-between md:p-7">
          <div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-brand-100 text-xl font-semibold text-brand-700">{student.name.slice(0, 1)}</span><div><h1 className="text-2xl font-semibold tracking-tight">{student.name}</h1><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm text-slate-500"><span>{studentTarget(student)}</span><span>{student.intake}</span></div></div></div>
          <div className="flex flex-wrap gap-2"><button onClick={() => setEditOpen(true)} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-medium text-slate-600 transition hover:bg-slate-50"><Pencil size={16}/>编辑</button><Link href={`/students/${params.id}/report`} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-brand-600 px-5 text-sm font-medium text-white shadow-sm transition hover:bg-brand-700"><Sparkles size={17}/>AI 生成规划报告</Link></div>
        </section>
        <div className="mt-6 grid gap-6 xl:grid-cols-3"><div className="space-y-6 xl:col-span-2">
          <Card title="基础信息" icon={Users}><div className="grid gap-x-8 gap-y-5 sm:grid-cols-2 lg:grid-cols-3"><Info label="姓名" value={student.name}/><Info label="邮箱" value={student.email}/><Info label="年级" value={student.grade || "待完善"}/><Info label="GPA" value={student.gpa || "暂无"}/><Info label={languageLabel} value={languageScore}/><Info label="SAT" value={student.sat || "暂无"}/><Info label="负责顾问" value={student.counselor}/></div></Card>
          <Card title="申请状态" icon={ListTodo}><div className="grid gap-5 sm:grid-cols-3"><Info label="当前阶段" value={student.status}/><div><p className="text-xs text-slate-400">完成进度</p><div className="mt-2 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-500" style={{ width: `${student.progress}%` }}/></div><span className="text-sm font-medium text-slate-600">{student.progress}%</span></div></div><Info label="待办事项" value="3 项待完成"/></div></Card>
          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card md:p-6"><div className="mb-5 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-brand-50 text-brand-600"><Target size={17}/></span><h2 className="font-semibold">目标院校</h2></div>{!schoolEditing && <button onClick={() => { setDraftSchools(student.targetSchools.map((school) => ({ ...school }))); setSchoolEditing(true); }} className="inline-flex h-9 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm font-medium text-slate-600 hover:bg-slate-50"><Pencil size={15}/>编辑</button>}</div>{schoolEditing ? <SchoolEditor schools={draftSchools} onChange={setDraftSchools} onCancel={() => setSchoolEditing(false)} onSave={async () => { const saved = await updateTargetSchools(student.id, draftSchools.filter((school) => school.name.trim())); if (saved) setSchoolEditing(false); }}/>: student.targetSchools.length ? <div className="grid gap-3 sm:grid-cols-3">{student.targetSchools.map((school, index) => <SchoolCard key={`${school.name}-${index}`} school={school}/>)}</div> : <div className="rounded-xl border border-dashed border-slate-200 px-4 py-10 text-center text-sm text-slate-400">暂未添加目标院校</div>}</section>
          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card md:p-6"><div className="mb-5 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-brand-50 text-brand-600"><Award size={17}/></span><h2 className="font-semibold">荣誉展示</h2></div>{!honorsEditing && <button onClick={() => { setDraftHonors({ activities: student.honors.activities.map((item) => ({ ...item })), competitions: student.honors.competitions.map((item) => ({ ...item })) }); setHonorsEditing(true); }} className="inline-flex h-9 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm font-medium text-slate-600 hover:bg-slate-50"><Pencil size={15}/>编辑</button>}</div>{honorsEditing ? <HonorsEditor honors={draftHonors} onChange={setDraftHonors} onCancel={() => setHonorsEditing(false)} onSave={async () => { const cleaned = { activities: draftHonors.activities.filter((item) => item.title.trim()), competitions: draftHonors.competitions.filter((item) => item.title.trim()) }; const saved = await updateHonors(student.id, cleaned); if (saved) setHonorsEditing(false); }}/> : <div className="grid gap-4 sm:grid-cols-2"><HonorList title="活动经历" items={student.honors.activities}/><HonorList title="竞赛经历" items={student.honors.competitions}/></div>}</section>
          <Card title="申请时间线" icon={FileCheck2}><div className="space-y-5"><Timeline icon={CheckCircle2} tone="text-emerald-500" label="已完成事项" title="完成背景评估与目标方向确认" detail={`已确认申请${studentTarget(student)}相关专业`}/><Timeline icon={Circle} tone="text-brand-600" label="当前事项" title="补充活动经历与选校调研" detail="预计本月内完成" current/><Timeline icon={Circle} tone="text-slate-300" label="下一步任务" title="启动个人陈述与推荐信准备" detail="计划下月开始"/></div></Card>
        </div><div className="space-y-6"><Card title="AI 风险分析" icon={AlertTriangle}><div><p className="text-xs font-semibold uppercase tracking-wider text-rose-500">风险</p><ul className="mt-3 space-y-3">{["活动经历不足", "文书准备较晚"].map((item) => <li key={item} className="flex gap-2 rounded-xl bg-rose-50 px-3 py-2.5 text-sm text-rose-700"><AlertTriangle size={16} className="mt-0.5 shrink-0"/>{item}</li>)}</ul></div><div className="mt-6 border-t border-slate-100 pt-5"><p className="text-xs font-semibold uppercase tracking-wider text-brand-600">AI 建议</p><ul className="mt-3 space-y-3">{["完成活动补充", "启动文书准备"].map((item) => <li key={item} className="flex gap-2 rounded-xl bg-brand-50 px-3 py-2.5 text-sm text-brand-700"><Sparkles size={16} className="mt-0.5 shrink-0"/>{item}</li>)}</ul></div></Card></div></div>
      </div>
    </main>
    <Dialog.Root open={editOpen} onOpenChange={setEditOpen}><EditStudentDialog student={student} onSave={async (values) => { const saved = await updateStudent(student.id, values); if (saved) setEditOpen(false); return saved; }}/></Dialog.Root>
  </div>;
}

function SchoolCard({ school }: { school: TargetSchool }) {
  const levelStyle: Record<SchoolLevel, string> = { "冲刺": "bg-rose-50 text-rose-600", "匹配": "bg-blue-50 text-blue-600", "稳妥": "bg-emerald-50 text-emerald-600" };
  const initials = school.name.split(/\s+/).filter(Boolean).map((word) => word[0]).join("").slice(0, 3).toUpperCase() || "—";
  return <div className="rounded-xl border border-slate-100 bg-slate-50/70 p-4"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-xl bg-white text-xs font-bold text-brand-700 shadow-sm">{school.logo ? <img src={school.logo} alt={`${school.name} Logo`} className="h-full w-full object-contain"/> : initials}</span><div className="min-w-0 flex-1"><p className="break-words text-sm font-semibold text-slate-700">{school.name}</p><span className={`mt-2 inline-flex rounded-full px-2 py-1 text-[11px] font-medium ${levelStyle[school.level]}`}>{school.level}</span></div></div></div>;
}

function SchoolEditor({ schools, onChange, onCancel, onSave }: { schools: TargetSchool[]; onChange: (schools: TargetSchool[]) => void; onCancel: () => void; onSave: () => Promise<void> }) {
  const field = "h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100";
  const update = (index: number, values: Partial<TargetSchool>) => onChange(schools.map((school, currentIndex) => currentIndex === index ? { ...school, ...values } : school));
  return <div><div className="space-y-3">{schools.map((school, index) => <div key={index} className="grid gap-3 rounded-xl border border-slate-100 bg-slate-50/60 p-4 sm:grid-cols-[1fr_140px_auto]"><label className="text-xs text-slate-500">学校名称<input value={school.name} onChange={(event) => update(index, { name: event.target.value })} placeholder="例如：University of California Berkeley" className={`mt-1.5 ${field}`}/></label><label className="text-xs text-slate-500">申请定位<select value={school.level} onChange={(event) => update(index, { level: event.target.value as SchoolLevel })} className={`mt-1.5 ${field}`}><option>冲刺</option><option>匹配</option><option>稳妥</option></select></label><button onClick={() => onChange(schools.filter((_, currentIndex) => currentIndex !== index))} className="mt-5 grid h-10 w-10 place-items-center rounded-xl text-rose-500 hover:bg-rose-50" aria-label={`删除${school.name || "学校"}`}><Trash2 size={16}/></button></div>)}</div><button onClick={() => onChange([...schools, { name: "", level: "匹配", logo: "" }])} className="mt-3 inline-flex h-10 items-center gap-2 rounded-xl border border-dashed border-brand-300 px-4 text-sm font-medium text-brand-700 hover:bg-brand-50"><Plus size={16}/>新增学校</button><div className="mt-5 flex justify-end gap-2 border-t border-slate-100 pt-5"><button onClick={onCancel} className="h-10 rounded-xl border border-slate-200 px-4 text-sm font-medium text-slate-600 hover:bg-slate-50">取消</button><button onClick={onSave} className="h-10 rounded-xl bg-brand-600 px-4 text-sm font-medium text-white hover:bg-brand-700">保存院校</button></div></div>;
}

function HonorList({ title, items }: { title: string; items: HonorItem[] }) {
  return <div className="rounded-xl border border-slate-100 bg-slate-50/60 p-4"><p className="text-sm font-semibold text-slate-700">{title}</p>{items.length ? <ul className="mt-3 space-y-2">{items.map((item, index) => <li key={`${item.title}-${index}`} className="flex items-start justify-between gap-3 rounded-lg bg-white px-3 py-2.5 text-sm"><span className="text-slate-600">{item.title}</span><span className="shrink-0 rounded-full bg-brand-50 px-2 py-0.5 text-xs font-medium text-brand-700">{item.year || "年份待补充"}</span></li>)}</ul> : <p className="mt-4 text-sm text-slate-400">暂未添加</p>}</div>;
}

function HonorsEditor({ honors, onChange, onCancel, onSave }: { honors: StudentHonors; onChange: (honors: StudentHonors) => void; onCancel: () => void; onSave: () => Promise<void> }) {
  const updateItems = (key: keyof StudentHonors, items: HonorItem[]) => onChange({ ...honors, [key]: items });
  return <div><div className="grid gap-4 sm:grid-cols-2"><HonorCategoryEditor title="活动经历" items={honors.activities} onChange={(items) => updateItems("activities", items)}/><HonorCategoryEditor title="竞赛经历" items={honors.competitions} onChange={(items) => updateItems("competitions", items)}/></div><div className="mt-5 flex justify-end gap-2 border-t border-slate-100 pt-5"><button onClick={onCancel} className="h-10 rounded-xl border border-slate-200 px-4 text-sm font-medium text-slate-600 hover:bg-slate-50">取消</button><button onClick={onSave} className="h-10 rounded-xl bg-brand-600 px-4 text-sm font-medium text-white hover:bg-brand-700">保存荣誉</button></div></div>;
}

function HonorCategoryEditor({ title, items, onChange }: { title: string; items: HonorItem[]; onChange: (items: HonorItem[]) => void }) {
  const field = "h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100";
  const update = (index: number, values: Partial<HonorItem>) => onChange(items.map((item, currentIndex) => currentIndex === index ? { ...item, ...values } : item));
  return <div className="rounded-xl border border-slate-100 bg-slate-50/60 p-4"><p className="text-sm font-semibold text-slate-700">{title}</p><div className="mt-3 space-y-3">{items.map((item, index) => <div key={index} className="grid grid-cols-[1fr_88px_auto] gap-2"><input aria-label={`${title}名称${index + 1}`} value={item.title} onChange={(event) => update(index, { title: event.target.value })} placeholder="经历名称" className={field}/><input aria-label={`${title}年份${index + 1}`} value={item.year} onChange={(event) => update(index, { year: event.target.value })} placeholder="年份" className={field}/><button onClick={() => onChange(items.filter((_, currentIndex) => currentIndex !== index))} className="grid h-10 w-10 place-items-center rounded-xl text-rose-500 hover:bg-rose-50" aria-label={`删除${title}${index + 1}`}><Trash2 size={16}/></button></div>)}</div><button onClick={() => onChange([...items, { title: "", year: "" }])} className="mt-3 inline-flex h-9 items-center gap-2 rounded-xl border border-dashed border-brand-300 px-3 text-sm font-medium text-brand-700 hover:bg-brand-50"><Plus size={15}/>添加{title}</button></div>;
}

function EditStudentDialog({ student, onSave }: { student: Student; onSave: (values: Partial<StudentFormValues>) => Promise<boolean> }) {
  const [values, setValues] = useState({ name: student.name, email: student.email, grade: student.grade, gpa: student.gpa, languageTest: student.languageTest, sat: student.sat });
  const field = "mt-1.5 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100";
  const update = (key: "name" | "email" | "grade" | "gpa" | "sat", value: string) => setValues((current) => ({ ...current, [key]: value }));
  const setLanguageType = (type: LanguageTestType) => setValues((current) => ({ ...current, languageTest: { type, score: type ? current.languageTest.score : "" } }));
  return <Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-ink/30 backdrop-blur-sm"/><Dialog.Content className="fixed left-1/2 top-1/2 z-50 max-h-[calc(100vh-2rem)] w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 -translate-y-1/2 overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><Dialog.Title className="text-lg font-semibold">编辑学生信息</Dialog.Title><Dialog.Description className="mt-1 text-sm text-slate-500">保存后，详情页与学生列表会同步更新。</Dialog.Description></div><Dialog.Close className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={18}/></Dialog.Close></div><form onSubmit={(event) => { event.preventDefault(); onSave(values); }} className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-600">姓名<input required value={values.name} onChange={(event) => update("name", event.target.value)} className={field}/></label><label className="text-sm text-slate-600">邮箱<input required type="email" value={values.email} onChange={(event) => update("email", event.target.value)} className={field}/></label><label className="text-sm text-slate-600">年级<input value={values.grade} onChange={(event) => update("grade", event.target.value)} className={field}/></label><label className="text-sm text-slate-600">GPA<input value={values.gpa} onChange={(event) => update("gpa", event.target.value)} className={field}/></label><label className="text-sm text-slate-600">语言考试类型<select value={values.languageTest.type} onChange={(event) => setLanguageType(event.target.value as LanguageTestType)} className={field}><option value="">暂无</option><option>IELTS</option><option>TOEFL</option><option>Duolingo</option></select></label>{values.languageTest.type && <label className="text-sm text-slate-600">{values.languageTest.type} 成绩<input required value={values.languageTest.score} onChange={(event) => setValues((current) => ({ ...current, languageTest: { ...current.languageTest, score: event.target.value } }))} className={field}/></label>}<label className="text-sm text-slate-600">SAT<input value={values.sat} onChange={(event) => update("sat", event.target.value)} className={field}/></label><div className="mt-2 flex justify-end gap-2 sm:col-span-2"><Dialog.Close className="h-10 rounded-xl border border-slate-200 px-4 text-sm font-medium text-slate-600 hover:bg-slate-50">取消</Dialog.Close><button type="submit" className="h-10 rounded-xl bg-brand-600 px-4 text-sm font-medium text-white hover:bg-brand-700">保存修改</button></div></form></Dialog.Content></Dialog.Portal>;
}

function Card({ title, icon: Icon, children }: { title: string; icon: typeof Users; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card md:p-6"><div className="mb-5 flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-brand-50 text-brand-600"><Icon size={17}/></span><h2 className="font-semibold">{title}</h2></div>{children}</section>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-slate-400">{label}</p><p className="mt-1.5 text-sm font-medium text-slate-700">{value}</p></div>; }
function Timeline({ icon: Icon, tone, label, title, detail, current = false }: { icon: typeof Circle; tone: string; label: string; title: string; detail: string; current?: boolean }) { return <div className={`flex gap-3 rounded-xl p-3 ${current ? "bg-brand-50" : ""}`}><Icon size={18} className={`mt-0.5 shrink-0 ${tone}`} fill={current ? "currentColor" : "none"}/><div><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-sm font-medium text-slate-700">{title}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div></div>; }
